### ISSUE TITLE
0.7.5 checklist

### ISSUE THREAD

**Issue by luisivan** [aragonone/product#129] opened 2019-06-24 20:06 UTC
- [x] Fix workers in Safari ([PR](https://github.com/aragon/aragon/pull/844))
- [x] Help Scout fixes

**Comment by AquiGorka** [comment] 2019-06-25 07:44
Can you help me understand how DAO choose is broken? This is what I see:

![2019-06-25 09 43 59](https://user-images.githubusercontent.com/3072458/60079252-d25acf80-972d-11e9-9c69-540bba4c2c09.gif)

**Comment by luisivan** [comment] 2019-06-25 12:28
Worked on Firefox for me, but doesn't seem to be working on Chromium or Brave

![Screencast from 06-25-2019 02_26_39 PM](https://user-images.githubusercontent.com/718208/60098299-77d56980-9755-11e9-8085-89b1050a194d.gif)

**Comment by AquiGorka** [comment] 2019-06-26 07:18
@luisivan 
Tested in macos with Chrome, Firefox, Safari and Brave (updated yesterday).
iOS: Coinbase, Status and Mobile Safari
Android: Coinbase and Status

Worked every time. I will test using a VM and Linux to see if I can reproduce.

**Comment by luisivan** [comment] 2019-06-26 09:43
Removed it from the scope until we can consistently replicate @AquiGorka

**Comment by luisivan** [comment] 2019-06-27 08:02
needs https://github.com/aragon/aragon-apps/issues/888

**Comment by luisivan** [comment] 2019-06-27 08:05
needs aragon/aragon-apps#888

**Comment by luisivan** [comment] 2019-06-27 08:09
needs https://github.com/aragonone/aragon-javascript-styleguide/issues/2

**Comment by luisivan** [comment] 2019-06-27 08:11
(Just testing, sorry for the noise)

**Comment by luisivan** [comment] 2019-06-27 08:28
needs https://github.com/aragon/aragon-apps/issues/888

**Comment by luisivan** [comment] 2019-06-27 08:29
needs https://github.com/aragon/aragon/pull/844

**Comment by luisivan** [comment] 2019-06-27 08:30
needs https://github.com/aragon/aragon/issues/843

**Comment by sohkai** [comment] 2019-06-27 14:35
@luisivan 

> Worked on Firefox for me, but doesn't seem to be working on Chromium or Brave

I believe this should be fixed with https://github.com/aragon/aragon/pull/844.

https://github.com/aragon/aragon/issues/843 should be fixed now, also due to https://github.com/aragon/aragon/pull/844.

**Comment by luisivan** [comment] 2019-06-28 09:30
Nice! Thanks for the update @sohkai

**Closed as completed** 2019-06-28 13:44 UTC
Labels: client
